# Generated by Django 4.2.1 on 2023-06-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textimage',
            name='image',
        ),
    ]
