# Generated by Django 4.2.1 on 2023-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_textimage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpscaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inp', models.ImageField(upload_to='')),
            ],
        ),
    ]
