# Generated by Django 4.2.1 on 2023-06-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_upscaleimage_inp'),
    ]

    operations = [
        migrations.AddField(
            model_name='upscaleimage',
            name='out',
            field=models.ImageField(default='123.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
